//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.bingoffers.com/v1/reports/IBillingStatement/", ConfigurationName="IBillingStatement")]
public interface IBillingStatement
{
    
    // CODEGEN: Generating message contract since the operation GetStatements is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute()]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetStatementsResponse1 GetStatements(GetStatementsRequest1 request);
    
    // CODEGEN: Generating message contract since the operation DownloadStatement is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute()]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    DownloadStatementResponse1 DownloadStatement(DownloadStatementRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.bingoffers.com/v1/reports/IBillingStatement/")]
public partial class GetStatementsRequest
{
    
    private string provIdField;
    
    private string merchantIdField;
    
    private string bECodeField;
    
    private string chainLevelField;
    
    private string fromDateField;
    
    private string toDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string provId
    {
        get
        {
            return this.provIdField;
        }
        set
        {
            this.provIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string merchantId
    {
        get
        {
            return this.merchantIdField;
        }
        set
        {
            this.merchantIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string BECode
    {
        get
        {
            return this.bECodeField;
        }
        set
        {
            this.bECodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string chainLevel
    {
        get
        {
            return this.chainLevelField;
        }
        set
        {
            this.chainLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string fromDate
    {
        get
        {
            return this.fromDateField;
        }
        set
        {
            this.fromDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string toDate
    {
        get
        {
            return this.toDateField;
        }
        set
        {
            this.toDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.bingoffers.com/v1/reports/IBillingStatement/")]
public partial class GetStatementsResponse
{
    
    private string provIdField;
    
    private string merchantIdField;
    
    private string bECodeField;
    
    private string chainLevelField;
    
    private string respCodeField;
    
    private string respTxtField;
    
    private GetStatementsResponseStatement[] statementField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string provId
    {
        get
        {
            return this.provIdField;
        }
        set
        {
            this.provIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string merchantId
    {
        get
        {
            return this.merchantIdField;
        }
        set
        {
            this.merchantIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string BECode
    {
        get
        {
            return this.bECodeField;
        }
        set
        {
            this.bECodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string chainLevel
    {
        get
        {
            return this.chainLevelField;
        }
        set
        {
            this.chainLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string respCode
    {
        get
        {
            return this.respCodeField;
        }
        set
        {
            this.respCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string respTxt
    {
        get
        {
            return this.respTxtField;
        }
        set
        {
            this.respTxtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("statement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public GetStatementsResponseStatement[] statement
    {
        get
        {
            return this.statementField;
        }
        set
        {
            this.statementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.bingoffers.com/v1/reports/IBillingStatement/")]
public partial class GetStatementsResponseStatement
{
    
    private string stmtKeyField;
    
    private string stmtLenField;
    
    private string stmtDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string stmtKey
    {
        get
        {
            return this.stmtKeyField;
        }
        set
        {
            this.stmtKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string stmtLen
    {
        get
        {
            return this.stmtLenField;
        }
        set
        {
            this.stmtLenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string stmtDate
    {
        get
        {
            return this.stmtDateField;
        }
        set
        {
            this.stmtDateField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetStatementsRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bingoffers.com/v1/reports/IBillingStatement/", Order=0)]
    public GetStatementsRequest GetStatementsRequest;
    
    public GetStatementsRequest1()
    {
    }
    
    public GetStatementsRequest1(GetStatementsRequest GetStatementsRequest)
    {
        this.GetStatementsRequest = GetStatementsRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetStatementsResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bingoffers.com/v1/reports/IBillingStatement/", Order=0)]
    public GetStatementsResponse GetStatementsResponse;
    
    public GetStatementsResponse1()
    {
    }
    
    public GetStatementsResponse1(GetStatementsResponse GetStatementsResponse)
    {
        this.GetStatementsResponse = GetStatementsResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.bingoffers.com/v1/reports/IBillingStatement/")]
public partial class DownloadStatementRequest
{
    
    private string provIdField;
    
    private string merchantIdField;
    
    private string bECodeField;
    
    private string chainLevelField;
    
    private string stmtKeyField;
    
    private string stmtDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string provId
    {
        get
        {
            return this.provIdField;
        }
        set
        {
            this.provIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string merchantId
    {
        get
        {
            return this.merchantIdField;
        }
        set
        {
            this.merchantIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string BECode
    {
        get
        {
            return this.bECodeField;
        }
        set
        {
            this.bECodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string chainLevel
    {
        get
        {
            return this.chainLevelField;
        }
        set
        {
            this.chainLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string stmtKey
    {
        get
        {
            return this.stmtKeyField;
        }
        set
        {
            this.stmtKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string stmtDate
    {
        get
        {
            return this.stmtDateField;
        }
        set
        {
            this.stmtDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.bingoffers.com/v1/reports/IBillingStatement/")]
public partial class DownloadStatementResponse
{
    
    private string provIdField;
    
    private string merchantIdField;
    
    private string bECodeField;
    
    private string stmtKeyField;
    
    private byte[] pdfDocField;
    
    private string respCodeField;
    
    private string respTxtField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string provId
    {
        get
        {
            return this.provIdField;
        }
        set
        {
            this.provIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string merchantId
    {
        get
        {
            return this.merchantIdField;
        }
        set
        {
            this.merchantIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string BECode
    {
        get
        {
            return this.bECodeField;
        }
        set
        {
            this.bECodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string stmtKey
    {
        get
        {
            return this.stmtKeyField;
        }
        set
        {
            this.stmtKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
    public byte[] pdfDoc
    {
        get
        {
            return this.pdfDocField;
        }
        set
        {
            this.pdfDocField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string respCode
    {
        get
        {
            return this.respCodeField;
        }
        set
        {
            this.respCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string respTxt
    {
        get
        {
            return this.respTxtField;
        }
        set
        {
            this.respTxtField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class DownloadStatementRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bingoffers.com/v1/reports/IBillingStatement/", Order=0)]
    public DownloadStatementRequest DownloadStatementRequest;
    
    public DownloadStatementRequest1()
    {
    }
    
    public DownloadStatementRequest1(DownloadStatementRequest DownloadStatementRequest)
    {
        this.DownloadStatementRequest = DownloadStatementRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class DownloadStatementResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bingoffers.com/v1/reports/IBillingStatement/", Order=0)]
    public DownloadStatementResponse DownloadStatementResponse;
    
    public DownloadStatementResponse1()
    {
    }
    
    public DownloadStatementResponse1(DownloadStatementResponse DownloadStatementResponse)
    {
        this.DownloadStatementResponse = DownloadStatementResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBillingStatementChannel : IBillingStatement, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BillingStatementClient : System.ServiceModel.ClientBase<IBillingStatement>, IBillingStatement
{
    
    public BillingStatementClient()
    {
    }
    
    public BillingStatementClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BillingStatementClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BillingStatementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BillingStatementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetStatementsResponse1 IBillingStatement.GetStatements(GetStatementsRequest1 request)
    {
        return base.Channel.GetStatements(request);
    }
    
    public GetStatementsResponse GetStatements(GetStatementsRequest GetStatementsRequest)
    {
        GetStatementsRequest1 inValue = new GetStatementsRequest1();
        inValue.GetStatementsRequest = GetStatementsRequest;
        GetStatementsResponse1 retVal = ((IBillingStatement)(this)).GetStatements(inValue);
        return retVal.GetStatementsResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    DownloadStatementResponse1 IBillingStatement.DownloadStatement(DownloadStatementRequest1 request)
    {
        return base.Channel.DownloadStatement(request);
    }
    
    public DownloadStatementResponse DownloadStatement(DownloadStatementRequest DownloadStatementRequest)
    {
        DownloadStatementRequest1 inValue = new DownloadStatementRequest1();
        inValue.DownloadStatementRequest = DownloadStatementRequest;
        DownloadStatementResponse1 retVal = ((IBillingStatement)(this)).DownloadStatement(inValue);
        return retVal.DownloadStatementResponse;
    }
}