//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace OffersEmail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BAXDropOff {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BAXDropOff() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OffersEmail.Resources.BAXDropOff", typeof(BAXDropOff).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Your Bing Ads Express account is ready to be activated.&lt;/b&gt; With just one step, your ads can go live..
        /// </summary>
        public static string AccountReady {
            get {
                return ResourceManager.GetString("AccountReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Ads Express allows you to promote your business to potential customers in your city. To give you a headstart, we&apos;ve provided you with a &lt;b&gt;$50 ad credit&lt;/b&gt;. With just one step, your ads can go live..
        /// </summary>
        public static string BingAdsExpressAllowsYou {
            get {
                return ResourceManager.GetString("BingAdsExpressAllowsYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bing Ads Express Team.
        /// </summary>
        public static string BingAdsExpressTeam {
            get {
                return ResourceManager.GetString("BingAdsExpressTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You could also check out our &lt;a href=&quot;http://advertise.bingads.microsoft.com/en-us/bingads-express-support&quot;&gt;FAQs&lt;/a&gt; or call us at &lt;b&gt;1-(888) 959-5732&lt;/b&gt;..
        /// </summary>
        public static string CheckOutOurFAQs {
            get {
                return ResourceManager.GetString("CheckOutOurFAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and sign in to your Bing Ads Express account in the next 3 weeks to claim your credit before it expires..
        /// </summary>
        public static string CreateAndSignIn {
            get {
                return ResourceManager.GetString("CreateAndSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have questions? Check out our &lt;a href=&quot;http://advertise.bingads.microsoft.com/en-us/bingads-express-support&quot;&gt;FAQs&lt;/a&gt; or call us at: &lt;b&gt;1-(888) 959-5732&lt;/b&gt;.
        /// </summary>
        public static string HaveQuestions {
            get {
                return ResourceManager.GetString("HaveQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have questions? Call us at: (888) 959-5732.
        /// </summary>
        public static string HaveQuestions_Original {
            get {
                return ResourceManager.GetString("HaveQuestions_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch your ad.
        /// </summary>
        public static string LaunchYourAd {
            get {
                return ResourceManager.GetString("LaunchYourAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Offer Details: Offer expires June 30, 2014, and applies only to advertisers opening a new Bing Ads Express account; a new Bing Ads Express account is one that has been open fewer than 30 days prior to the date of coupon redemption. Ads must be stopped after $50 ad credit is used up or within 90 days from coupon redemption, whichever comes first, or your credit card will be charged for advertising clicks. It is the sole responsibility of advertisers to monitor their Bing Ads Express accounts. Limit: one ad  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OfferDetails {
            get {
                return ResourceManager.GetString("OfferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our informative 2 minute &lt;a href=&quot;{0}&quot;&gt;video&lt;/a&gt; will help..
        /// </summary>
        public static string OurInformativeVideo {
            get {
                return ResourceManager.GetString("OurInformativeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely,.
        /// </summary>
        public static string Sincerely {
            get {
                return ResourceManager.GetString("Sincerely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still have questions?.
        /// </summary>
        public static string StillHaveQuestions {
            get {
                return ResourceManager.GetString("StillHaveQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for verifying your business {0} on Bing Places. Your Bing Ads Express account is ready to be activated. We noticed that you created your ad but did not add your credit card. To give you a headstart, we&apos;ve provided you with a &lt;b&gt;$50 ad credit&lt;/b&gt;. With just one step, your ads can go live..
        /// </summary>
        public static string ThanksForVerifyingAdCreated {
            get {
                return ResourceManager.GetString("ThanksForVerifyingAdCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for verifying your business {0} on Bing Places. We noticed that you visited the Create Ad page, but did not create an ad..
        /// </summary>
        public static string ThanksForVerifyingAdNotCreated {
            get {
                return ResourceManager.GetString("ThanksForVerifyingAdNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start reaching potential customers, &lt;a href=&quot;{0}&quot;&gt;sign in&lt;/a&gt; to your Bing Ads Express account, add any ad copy you may need along with your payment method, and you&apos;ll be ready to launch your first ad on Bing. We&apos;ve even provided you with a $50 ad credit to get started..
        /// </summary>
        public static string ToCompleteYourSignUp_Original {
            get {
                return ResourceManager.GetString("ToCompleteYourSignUp_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete your sign up and start reaching potential customers, &lt;a href=&quot;{0}&quot;&gt;sign in&lt;/a&gt; to your Bing Ads Express account and add  your credit card to launch your first ad on Bing..
        /// </summary>
        public static string ToCompleteYourSignUpAdCreated {
            get {
                return ResourceManager.GetString("ToCompleteYourSignUpAdCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete your sign up and start reaching potential customers, &lt;a href=&quot;{0}&quot;&gt;sign in&lt;/a&gt; to your Bing Ads Express account and add any ad copy along with your credit card to launch your first ad on Bing..
        /// </summary>
        public static string ToCompleteYourSignUpAdNotCreated {
            get {
                return ResourceManager.GetString("ToCompleteYourSignUpAdNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start reaching potential customers, &lt;a href=&quot;{0}&quot;&gt;sign in&lt;/a&gt; to your Bing Ads Express account, add any ad copy you may need along with your payment method, and you&apos;ll be ready to launch your first ad on Bing..
        /// </summary>
        public static string ToStartReaching {
            get {
                return ResourceManager.GetString("ToStartReaching", resourceCulture);
            }
        }
    }
}