//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace OffersEmail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BAXEmail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BAXEmail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OffersEmail.Resources.BAXEmail", typeof(BAXEmail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising made easy.
        /// </summary>
        public static string AdvertisingMadeEasy {
            get {
                return ResourceManager.GetString("AdvertisingMadeEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://fp.advertising.microsoft.com/WWImages/search/cl/bingads-express-homepage/4578/global/BAX-HP-Win12-kenji-dell02-996x380.jpg.
        /// </summary>
        public static string BaxHomePageImageUrl {
            get {
                return ResourceManager.GetString("BaxHomePageImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing.
        /// </summary>
        public static string Bing {
            get {
                return ResourceManager.GetString("Bing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Ads Express.
        /// </summary>
        public static string BingAdsExpress {
            get {
                return ResourceManager.GetString("BingAdsExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bing Ads Express Team.
        /// </summary>
        public static string BingAdsExpressTeam {
            get {
                return ResourceManager.GetString("BingAdsExpressTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://image.email.microsoftemail.com/lib/fe61157075630774741d/m/5/logo_bing_gray_tr_106x58.png.
        /// </summary>
        public static string BingLogoUrl {
            get {
                return ResourceManager.GetString("BingLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you know that Bing Search Advertising can help you reach &lt;b&gt;{0:n0} consumers&lt;/b&gt; near your business across the Bing and Yahoo networks? We would like to give you &lt;b&gt;150 Dollars of free advertising&lt;/b&gt; to run an ad and experience the results first hand. Getting started is easy and FREE – We&apos;ve created a ready-to-run ad and all you need to do is &lt;a href=&quot;{1}&quot;&gt;click through&lt;/a&gt;.
        /// </summary>
        public static string DidYouKnow {
            get {
                return ResourceManager.GetString("DidYouKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are receiving this email because you have signed up to receive Bing Places communications. If you prefer not to receive future offer emails, use the link below to unsubscribe..
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://bingads.uservoice.com/forums/220185-bing-ads-express.
        /// </summary>
        public static string FeedbackUrl {
            get {
                return ResourceManager.GetString("FeedbackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find local customers.
        /// </summary>
        public static string FindLocalCustomers {
            get {
                return ResourceManager.GetString("FindLocalCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the area around your business to drive local customers to your door..
        /// </summary>
        public static string FindLocalCustomersDescription {
            get {
                return ResourceManager.GetString("FindLocalCustomersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dispads.blob.core.windows.net/static/local.png.
        /// </summary>
        public static string FindLocalCustomersImage {
            get {
                return ResourceManager.GetString("FindLocalCustomersImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you had a chance to see our earlier email about promoting your business. .
        /// </summary>
        public static string FollowUpStatement {
            get {
                return ResourceManager.GetString("FollowUpStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot; style=&quot;color:#04c&quot;&gt;Get started with Bing Ads Express&lt;/a&gt;.
        /// </summary>
        public static string GetStartedNow {
            get {
                return ResourceManager.GetString("GetStartedNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started is easy. Just follow these steps to show your ad to customers..
        /// </summary>
        public static string GettingStartedIsEasy {
            get {
                return ResourceManager.GetString("GettingStartedIsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just follow these steps to show your ad to customers..
        /// </summary>
        public static string GettingStartedIsEasyWithCoupon {
            get {
                return ResourceManager.GetString("GettingStartedIsEasyWithCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started is easy.
        /// </summary>
        public static string GettingStartedTitle {
            get {
                return ResourceManager.GetString("GettingStartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a preview of how your search ad will look like..
        /// </summary>
        public static string HereIsAPreview {
            get {
                return ResourceManager.GetString("HereIsAPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does it work?.
        /// </summary>
        public static string HowDoesItWork {
            get {
                return ResourceManager.GetString("HowDoesItWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your ad, set your budget and we will optimize your campaign for you..
        /// </summary>
        public static string HowItWorksDescription {
            get {
                return ResourceManager.GetString("HowItWorksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dispads.blob.core.windows.net/static/how.png.
        /// </summary>
        public static string HowItWorksImage {
            get {
                return ResourceManager.GetString("HowItWorksImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works?.
        /// </summary>
        public static string HowItWorksQuestionSmall {
            get {
                return ResourceManager.GetString("HowItWorksQuestionSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your customers are online, now you can be too. We&apos;d like to help you reach the {0:n0} consumers that are searching on Bing and Yahoo in locations near your business..
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for verifying your business {0} on Bing Places. Do you know that {1:n0} people are searching for businesses like yours in {2} area? Advertise on the Yahoo! Bing network to reach out to these potential customers..
        /// </summary>
        public static string IntroductionWithCoupon {
            get {
                return ResourceManager.GetString("IntroductionWithCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s quick and easy.
        /// </summary>
        public static string ItsQuickAndEasy {
            get {
                return ResourceManager.GetString("ItsQuickAndEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote your business online in just a few steps and we&apos;ll do the rest..
        /// </summary>
        public static string ItsQuickAndEasyDescription {
            get {
                return ResourceManager.GetString("ItsQuickAndEasyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re the boss. Set your monthly budget and we will make sure you never pay more..
        /// </summary>
        public static string MainControlDescription {
            get {
                return ResourceManager.GetString("MainControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dispads.blob.core.windows.net/static/control.png.
        /// </summary>
        public static string MainControlImage {
            get {
                return ResourceManager.GetString("MainControlImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find new customers on the Yahoo! Bing network.
        /// </summary>
        public static string MainHeading {
            get {
                return ResourceManager.GetString("MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find new customers across Microsoft&apos;s websites and services.
        /// </summary>
        public static string MainHeadingRich {
            get {
                return ResourceManager.GetString("MainHeadingRich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain Control.
        /// </summary>
        public static string MaintainControl {
            get {
                return ResourceManager.GetString("MaintainControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string Microsoft {
            get {
                return ResourceManager.GetString("Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://TODO_YOUR_CDN_URL/autoprospecting-assets/ms.logo70x15.png.
        /// </summary>
        public static string MicrosoftLogoUrl {
            get {
                return ResourceManager.GetString("MicrosoftLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Corporation, 1 Microsoft Way, Redmond, WA 98052, USA.
        /// </summary>
        public static string MicrosoftsAddress {
            get {
                return ResourceManager.GetString("MicrosoftsAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Offer Details: Offer expires in 3 weeks and applies only to advertisers opening a new Bing Ads account. Ads must be stopped after ad credit is used up or 90 days after coupon redemption, whichever comes first, or credit card will be charged. Any portion of ad credit not used within 90 days will expire. &lt;a href=&quot;{0}&quot;&gt;Full offer details&lt;/a&gt;.
        /// </summary>
        public static string OfferDetails {
            get {
                return ResourceManager.GetString("OfferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or call us at &lt;b&gt;1-(888) 959-5732&lt;/b&gt;..
        /// </summary>
        public static string OrCallUsAt {
            get {
                return ResourceManager.GetString("OrCallUsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our informative 2 minute &lt;a href=&quot;{0}&quot;&gt;video&lt;/a&gt; will help..
        /// </summary>
        public static string OurInfomativeVideo {
            get {
                return ResourceManager.GetString("OurInfomativeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people on the Yahoo! Bing Network.
        /// </summary>
        public static string PeopleOn {
            get {
                return ResourceManager.GetString("PeopleOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statements.
        /// </summary>
        public static string PrivacyStatements {
            get {
                return ResourceManager.GetString("PrivacyStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://go.microsoft.com/fwlink/?LinkId=248686.
        /// </summary>
        public static string PrivacyStatementsUrl {
            get {
                return ResourceManager.GetString("PrivacyStatementsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dispads.blob.core.windows.net/static/easy.png.
        /// </summary>
        public static string QuickAndEasyImage {
            get {
                return ResourceManager.GetString("QuickAndEasyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0}.
        /// </summary>
        public static string ReachNo {
            get {
                return ResourceManager.GetString("ReachNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim your $150 credit now.
        /// </summary>
        public static string RedeemButton {
            get {
                return ResourceManager.GetString("RedeemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem your $150 coupon*.
        /// </summary>
        public static string RedeemYour150 {
            get {
                return ResourceManager.GetString("RedeemYour150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely,.
        /// </summary>
        public static string Sincerely {
            get {
                return ResourceManager.GetString("Sincerely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;1) Create your ad &amp; specify your target radius.&lt;/b&gt; We&apos;ve helped by starting one for you. Just &lt;a href=&quot;{0}&quot; style=&quot;color:#04c&quot;&gt;sign in&lt;/a&gt; with your Bing Places for Business credentials to make changes, check it for accuracy, and launch it..
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;2) Start your risk-free trial of Bing Ads Express.&lt;/b&gt; Sign-up in the next 3 weeks and your account will be credited with $150 for use towards advertising..
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;3) Get $150 in free search advertising*.&lt;/b&gt; Enter your payment information in the next 3 weeks and your account will be credited with $150 for use towards advertising. We will not charge your card until you exhaust the credited amount and your campaign continues to run. We hope you find it worthwhile to continue to attract new customers with Bing Ads Express beyond the free credit amount, but if you don&apos;t, you can reduce your budget or suspend your campaign at any time..
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://i.imgur.com/wTC7Hh0.png.
        /// </summary>
        public static string StepsImageUrl {
            get {
                return ResourceManager.GetString("StepsImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still have questions?.
        /// </summary>
        public static string StillHaveQuestions {
            get {
                return ResourceManager.GetString("StillHaveQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STILL HAVE QUESTIONS?.
        /// </summary>
        public static string StillHaveQuestionsCaps {
            get {
                return ResourceManager.GetString("StillHaveQuestionsCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://g.msn.com/1ewbingwin8/settingsTOUen-US.
        /// </summary>
        public static string TermsAndConditionsUrl {
            get {
                return ResourceManager.GetString("TermsAndConditionsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for verifying your business &lt;b&gt;{0}&lt;/b&gt; on Bing Places. {1}Did you know that around &lt;b&gt;170 million people&lt;/b&gt; search on the Yahoo! Bing network every month?.
        /// </summary>
        public static string ThanksForVerifyingRich {
            get {
                return ResourceManager.GetString("ThanksForVerifyingRich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best part? We&apos;ll do the rest for you. See how easy search advertising can be with &lt;a href=&quot;{0}&quot;&gt;Bing Ads Express&lt;/a&gt;.
        /// </summary>
        public static string TheBestPart {
            get {
                return ResourceManager.GetString("TheBestPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Ads Express.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.bingplaces.com/DashBoard/Unsubscribe?view=PopUpView.
        /// </summary>
        public static string UnsubscribeBingPlacesUrl {
            get {
                return ResourceManager.GetString("UnsubscribeBingPlacesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://profile.microsoft.com/RegSysProfileCenter/contactPref.aspx?lcid=1033.
        /// </summary>
        public static string UnsubscribeMicrosoftUrl {
            get {
                return ResourceManager.GetString("UnsubscribeMicrosoftUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are offering you $150 of advertising credit to begin with..
        /// </summary>
        public static string WeAreOffering {
            get {
                return ResourceManager.GetString("WeAreOffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re offering you $150 to start with*.
        /// </summary>
        public static string WereOfferingYou {
            get {
                return ResourceManager.GetString("WereOfferingYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo! | Bing Network.
        /// </summary>
        public static string YahooBingNetwork {
            get {
                return ResourceManager.GetString("YahooBingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://image.email.microsoftemail.com/lib/fe61157075630774741d/m/5/logo_YBN_gray_116x42.jpg.
        /// </summary>
        public static string YahooBingNetworkLogoUrl {
            get {
                return ResourceManager.GetString("YahooBingNetworkLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach out to these potential customers by promoting your business with Bing Ads Express..
        /// </summary>
        public static string YouMightBeMissingOut {
            get {
                return ResourceManager.GetString("YouMightBeMissingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on the recommended radius, your ad could potentially reach.
        /// </summary>
        public static string YourAdCouldReach {
            get {
                return ResourceManager.GetString("YourAdCouldReach", resourceCulture);
            }
        }
    }
}