//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace OffersEmail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BPClaim {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BPClaim() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OffersEmail.Resources.BPClaim", typeof(BPClaim).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing.
        /// </summary>
        public static string Bing {
            get {
                return ResourceManager.GetString("Bing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bing Ads Express Team.
        /// </summary>
        public static string BingAdsExpressTeam {
            get {
                return ResourceManager.GetString("BingAdsExpressTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://image.email.microsoftemail.com/lib/fe61157075630774741d/m/5/logo_bing_gray_tr_106x58.png.
        /// </summary>
        public static string BingLogoUrl {
            get {
                return ResourceManager.GetString("BingLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Places.
        /// </summary>
        public static string BingPlaces {
            get {
                return ResourceManager.GetString("BingPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://fp.advertising.microsoft.com/WWImages/search/cl/bingads-express-homepage/4578/global/BAX-HP-Win12-kenji-dell02-996x380.jpg.
        /// </summary>
        public static string BingPlacesImageUrl {
            get {
                return ResourceManager.GetString("BingPlacesImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bing Places Team.
        /// </summary>
        public static string BingPlacesTeam {
            get {
                return ResourceManager.GetString("BingPlacesTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.bingplaces.com.
        /// </summary>
        public static string BingPlacesUrl {
            get {
                return ResourceManager.GetString("BingPlacesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Businesses claimed on Bing Places are featured more prominently in Yahoo! Bing search results. You might be missing out on these potential customers by not claiming your business..
        /// </summary>
        public static string BusinessClaimedOnBingPlaces {
            get {
                return ResourceManager.GetString("BusinessClaimedOnBingPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim your business.
        /// </summary>
        public static string ClaimYourListing {
            get {
                return ResourceManager.GetString("ClaimYourListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you know that around &lt;b&gt;170 million people&lt;/b&gt; search on the Yahoo! Bing network every month? You might be missing out on these potential customers by not claiming your business on Bing Places. With just a few minutes of your time, you can enhance how your business appears to customers with content like photos, services offered and much more..
        /// </summary>
        public static string DidYouKnow {
            get {
                return ResourceManager.GetString("DidYouKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are receiving this email because you visited Bing Places as part of the Bing Places Facebook promotion..
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find new customers on the Yahoo! Bing network.
        /// </summary>
        public static string MainHeading {
            get {
                return ResourceManager.GetString("MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string Microsoft {
            get {
                return ResourceManager.GetString("Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://TODO_YOUR_CDN_URL/autoprospecting-assets/ms.logo70x15.png.
        /// </summary>
        public static string MicrosoftLogoUrl {
            get {
                return ResourceManager.GetString("MicrosoftLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Corporation, 1 Microsoft Way, Redmond, WA 98052, USA.
        /// </summary>
        public static string MicrosoftsAddress {
            get {
                return ResourceManager.GetString("MicrosoftsAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Places.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statements.
        /// </summary>
        public static string PrivacyStatements {
            get {
                return ResourceManager.GetString("PrivacyStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach out to these potential customers by advertising on Bing Ads Express..
        /// </summary>
        public static string ReachOut {
            get {
                return ResourceManager.GetString("ReachOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely,.
        /// </summary>
        public static string Sincerely {
            get {
                return ResourceManager.GetString("Sincerely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still have questions?.
        /// </summary>
        public static string StillHaveQuestions {
            get {
                return ResourceManager.GetString("StillHaveQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.bingplaces.com/DashBoard/Support.
        /// </summary>
        public static string SupportUrl {
            get {
                return ResourceManager.GetString("SupportUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for visiting Bing Places from our Facebook promotion. Did you know that around &lt;b&gt;170 million people&lt;/b&gt; search on the Yahoo! Bing network every month?.
        /// </summary>
        public static string ThanksForVisiting {
            get {
                return ResourceManager.GetString("ThanksForVisiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Ads Express.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://image.email.microsoftemail.com/lib/fe61157075630774741d/m/5/logo_YBN_gray_116x42.jpg.
        /// </summary>
        public static string YahooBingLogoUrl {
            get {
                return ResourceManager.GetString("YahooBingLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo! Bing Network.
        /// </summary>
        public static string YahooBingNetwork {
            get {
                return ResourceManager.GetString("YahooBingNetwork", resourceCulture);
            }
        }
    }
}