//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace OffersEmail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CardLink {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardLink() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OffersEmail.Resources.CardLink", typeof(CardLink).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register another card.
        /// </summary>
        public static string AddAnotherCard {
            get {
                return ResourceManager.GetString("AddAnotherCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember that you can register as many cards as you’d like with Bing Offers and then use any of those cards to redeem your discount..
        /// </summary>
        public static string AddCard_AddAnotherCard {
            get {
                return ResourceManager.GetString("AddCard_AddAnotherCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit any participating business and make a qualifying purchase using a credit or debit card you&apos;ve registered during signup..
        /// </summary>
        public static string AddCard_Howwork1 {
            get {
                return ResourceManager.GetString("AddCard_Howwork1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out the instant &quot;you just saved&quot; notification on your cell phone..
        /// </summary>
        public static string AddCard_Howwork2 {
            get {
                return ResourceManager.GetString("AddCard_Howwork2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your discount will appear on your next credit card statement..
        /// </summary>
        public static string AddCard_Howwork3 {
            get {
                return ResourceManager.GetString("AddCard_Howwork3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s it! No coupons to buy in advance, no vouchers to bring with you to the merchant. We&apos;ll take care of it for you. Just walk in and use your card as you normally do. And reap the discounts!.
        /// </summary>
        public static string AddCard_NoCoupons {
            get {
                return ResourceManager.GetString("AddCard_NoCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for registering your {0} card ending in {1} with Bing Offers Card-Linked. .
        /// </summary>
        public static string AddCard_Thanks {
            get {
                return ResourceManager.GetString("AddCard_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for registering a debit or credit card with Bing Offers Card-Linked. .
        /// </summary>
        public static string AddCard_ThanksUnverified {
            get {
                return ResourceManager.GetString("AddCard_ThanksUnverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Card.
        /// </summary>
        public static string AddCard_Title {
            get {
                return ResourceManager.GetString("AddCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} card ending in {1} is successfully linked with Bing Offers Card-Linked and is ready to use..
        /// </summary>
        public static string AddCardSmsContent {
            get {
                return ResourceManager.GetString("AddCardSmsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your card is successfully linked with Bing Offers Card-Linked and is now ready to use..
        /// </summary>
        public static string AddCardSmsContentUnVerifiedUser {
            get {
                return ResourceManager.GetString("AddCardSmsContentUnVerifiedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you&apos;re ready to get the discounts you&apos;re looking for at places where you eat, play, and shop. And you never have to prepay!.
        /// </summary>
        public static string AddCardThanks2 {
            get {
                return ResourceManager.GetString("AddCardThanks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your purchase is voided, cancelled, refunded, or adjusted you may not qualify for this offer and may not receive this discount..
        /// </summary>
        public static string AdjustmentDisclaimer {
            get {
                return ResourceManager.GetString("AdjustmentDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///Your discount of {2} at {1} is on its way *.
        ///
        ///Once your transaction is processed, we’ll credit {3} to your credit card ending in {4}.
        ///
        ///Visit https://www.bing.com/offers/ to find more great deals or if you have any questions!
        ///
        ///-----------------------------------------------------------------------------------------------
        ///* If this transaction is voided, cancelled, or adjusted you may not qualify for this offer and may not receive this discount. If the amount of this transaction changes (like [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AuthEmailTextContent {
            get {
                return ResourceManager.GetString("AuthEmailTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///Your Bing Offers Card-Linked discount is on its way *.
        ///
        ///To track the status of your discount and see your redemption details, please verify your email address by visiting this link here:  {3} .                                                                                                                                                                                                                                                                                                                    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AuthEmailUnAuthenticatedSignUpEmailUnconfirmedTextContent {
            get {
                return ResourceManager.GetString("AuthEmailUnAuthenticatedSignUpEmailUnconfirmedTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///Your discount of {2} at {1} is on its way *.
        ///
        ///To track the status of your discount and see your redemption details, please link your email account to either a Microsoft account or Facebook login by visiting this link here :  {3} .                                                                                                                                                                                                                                                                               [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AuthEmailUnAuthenticatedSignUpEmailUnlinkedTextContent {
            get {
                return ResourceManager.GetString("AuthEmailUnAuthenticatedSignUpEmailUnlinkedTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is on its way.
        /// </summary>
        public static string AuthParagraph1Part2 {
            get {
                return ResourceManager.GetString("AuthParagraph1Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once your transaction is processed, we’ll credit.
        /// </summary>
        public static string AuthParagraph2Part1 {
            get {
                return ResourceManager.GetString("AuthParagraph2Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this transaction is voided, cancelled, or adjusted you may not qualify for this offer and may not receive this discount. If the amount of this transaction changes (like when you add a tip at a restaurant) your discount may vary..
        /// </summary>
        public static string AuthParagraph3 {
            get {
                return ResourceManager.GetString("AuthParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your discount of.
        /// </summary>
        public static string AuthSettleParagraph1Part {
            get {
                return ResourceManager.GetString("AuthSettleParagraph1Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to your credit card ending in.
        /// </summary>
        public static string AuthSettleParagraph2Part {
            get {
                return ResourceManager.GetString("AuthSettleParagraph2Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BING OFFERS: &quot;{1}&quot; at {0} redeemed. http://aka.ms/card-linked for info..
        /// </summary>
        public static string AuthSmsTextContent {
            get {
                return ResourceManager.GetString("AuthSmsTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount on its way.
        /// </summary>
        public static string AuthTitle {
            get {
                return ResourceManager.GetString("AuthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Offers.
        /// </summary>
        public static string BingOffers {
            get {
                return ResourceManager.GetString("BingOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bing.com/offers.
        /// </summary>
        public static string BingOffersAddress {
            get {
                return ResourceManager.GetString("BingOffersAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Offers support..
        /// </summary>
        public static string Bingofferssupport {
            get {
                return ResourceManager.GetString("Bingofferssupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.bing.com/offers/.
        /// </summary>
        public static string BingOffersUrl {
            get {
                return ResourceManager.GetString("BingOffersUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://TODO_YOUR_CDN_URL/card-linked-assets/BlueGold_BingOffers_CardLink.png.
        /// </summary>
        public static string CardLinkedLogoUrl {
            get {
                return ResourceManager.GetString("CardLinkedLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide feedback to the merchant about your experience by clicking over.
        /// </summary>
        public static string CardLinkFeedbackPart1 {
            get {
                return ResourceManager.GetString("CardLinkFeedbackPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string CardLinkFeedbackPart2 {
            get {
                return ResourceManager.GetString("CardLinkFeedbackPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string CardLinkFeedbackPart3 {
            get {
                return ResourceManager.GetString("CardLinkFeedbackPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        public static string CommonParagraph1Part1 {
            get {
                return ResourceManager.GetString("CommonParagraph1Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to find more great deals or if you have any questions!.
        /// </summary>
        public static string CommonParagraph1Part2 {
            get {
                return ResourceManager.GetString("CommonParagraph1Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email was sent from a notification-only address that cannot accept incoming email.  Please do not reply to this message..
        /// </summary>
        public static string CommonParagraph2 {
            get {
                return ResourceManager.GetString("CommonParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s next? Registering a debit or credit card with Bing Offers. &lt;a target=&apos;_blank&apos; href=&quot;{0}&quot;&gt;Do it now&lt;/a&gt; and begin getting the discounts you&apos;re looking for!.
        /// </summary>
        public static string CompleteProfile_Next {
            get {
                return ResourceManager.GetString("CompleteProfile_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit cards with the VISA or MasterCard logos are eligible as long as you sign (and don&apos;t enter a PIN) at checkout..
        /// </summary>
        public static string DebitDisclaimer {
            get {
                return ResourceManager.GetString("DebitDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want to let you know that you&apos;ve deleted a debit or credit card that you have been using with Bing Offers Card-Linked. The card still works, of course. But you can no longer get Bing Offers discounts credited to this card..
        /// </summary>
        public static string DeleteCard_CardDeleted {
            get {
                return ResourceManager.GetString("DeleteCard_CardDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have another card registered with Bing Offers, so you&apos;re still in business. Discounts for purchases made at any of our participating merchants will be credited to that card..
        /// </summary>
        public static string DeleteCard_HaveAnotherCard {
            get {
                return ResourceManager.GetString("DeleteCard_HaveAnotherCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This was the last or only card you had registered with Bing Offers. So you won&apos;t be able to get any Bing Offers discounts until you add a new card. Just &lt;a target=&apos;_blank&apos; href=&quot;{0}&quot;&gt;follow the simple steps&lt;/a&gt; and you&apos;ll be good to go!.
        /// </summary>
        public static string DeleteCard_NoCard {
            get {
                return ResourceManager.GetString("DeleteCard_NoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Card.
        /// </summary>
        public static string DeleteCard_Title {
            get {
                return ResourceManager.GetString("DeleteCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Bing Offers Card-Linked discount is approved..
        /// </summary>
        public static string DiscountApprovedMessagePrivacyCompliant {
            get {
                return ResourceManager.GetString("DiscountApprovedMessagePrivacyCompliant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Bing Offers Card-Linked discount is on its way..
        /// </summary>
        public static string DiscountOnitsWayMessagePrivacyCompliant {
            get {
                return ResourceManager.GetString("DiscountOnitsWayMessagePrivacyCompliant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string FAQLinkText {
            get {
                return ResourceManager.GetString("FAQLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string FAQPart1 {
            get {
                return ResourceManager.GetString("FAQPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to get your questions answered and find out more..
        /// </summary>
        public static string FAQPart2 {
            get {
                return ResourceManager.GetString("FAQPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Print.
        /// </summary>
        public static string FinePrint {
            get {
                return ResourceManager.GetString("FinePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this transaction is voided, canceled, or adjusted you may not qualify for this offer and may not receive this discount. If the amount of this transaction changes (like when you tip at a restaurant) your discount may vary..
        /// </summary>
        public static string FinePrint_DiscountVary {
            get {
                return ResourceManager.GetString("FinePrint_DiscountVary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email was sent from a notification-only address that cannot accept incoming email. Please do not reply to this message..
        /// </summary>
        public static string FinePrint_NoReply {
            get {
                return ResourceManager.GetString("FinePrint_NoReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft | 1 Microsoft Way, Redmond, WA 98052 |.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve already taken the first step: signing up at {0} to discover all of the great deals in your area..
        /// </summary>
        public static string HowToSave_1 {
            get {
                return ResourceManager.GetString("HowToSave_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit any participating business and make a qualifying purchase using a credit or debit card you’ve registered with Bing Offers..
        /// </summary>
        public static string HowToSave_2 {
            get {
                return ResourceManager.GetString("HowToSave_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out the instant &quot;you just saved&quot; notification on your cell phone. Your discount will appear on your next credit card statement..
        /// </summary>
        public static string HowToSave_3 {
            get {
                return ResourceManager.GetString("HowToSave_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s how you redeem our offers:.
        /// </summary>
        public static string HowToSaveExistingHeader {
            get {
                return ResourceManager.GetString("HowToSaveExistingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make an eligible purchase with your registered credit or debit card. No need to bring a coupon..
        /// </summary>
        public static string HowToSaveExistingParagraph1 {
            get {
                return ResourceManager.GetString("HowToSaveExistingParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll send you a message to let you know we&apos;re processing your discount..
        /// </summary>
        public static string HowToSaveExistingParagraph2 {
            get {
                return ResourceManager.GetString("HowToSaveExistingParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In most cases, we’ll apply the discount to your statement within three to five days of purchase..
        /// </summary>
        public static string HowToSaveExistingParagraph3 {
            get {
                return ResourceManager.GetString("HowToSaveExistingParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s how to save:.
        /// </summary>
        public static string HowToSaveHeader {
            get {
                return ResourceManager.GetString("HowToSaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up at.
        /// </summary>
        public static string HowToSaveParagraph1Part1 {
            get {
                return ResourceManager.GetString("HowToSaveParagraph1Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and discover all of the great deals in your area..
        /// </summary>
        public static string HowToSaveParagraph1Part2 {
            get {
                return ResourceManager.GetString("HowToSaveParagraph1Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit any participating business and make a qualifying purchase using one of the credit or debit card you registered during signup..
        /// </summary>
        public static string HowToSaveParagraph2 {
            get {
                return ResourceManager.GetString("HowToSaveParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll receive an instant notification on your mobile phone that you saved, and the discount will appear on your next credit card statement..
        /// </summary>
        public static string HowToSaveParagraph3 {
            get {
                return ResourceManager.GetString("HowToSaveParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And that&apos;s it! No need to pay in advance for a coupon or bring a voucher with you to the merchant. We&apos;ll take care of it for you. Just use your card as you normally do..
        /// </summary>
        public static string HowToSaveParagraph4 {
            get {
                return ResourceManager.GetString("HowToSaveParagraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are a few examples of great offers near you. You can see these and over 50 more offers in your area at.
        /// </summary>
        public static string HowToSaveParagraph4New {
            get {
                return ResourceManager.GetString("HowToSaveParagraph4New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string HowToSaveParagraph5FAQLinkText {
            get {
                return ResourceManager.GetString("HowToSaveParagraph5FAQLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string HowToSaveParagraph5Part1 {
            get {
                return ResourceManager.GetString("HowToSaveParagraph5Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to get your questions answered and find out more..
        /// </summary>
        public static string HowToSaveParagraph5Part2 {
            get {
                return ResourceManager.GetString("HowToSaveParagraph5Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s how it works:.
        /// </summary>
        public static string HowWorks {
            get {
                return ResourceManager.GetString("HowWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///The offer {2} at {1} is now linked to the credit cards you have added to your Bing Offers account.
        ///
        ///Just pay with one of these cards to get the discount. As soon as your qualifying transaction is complete we’ll notify you.
        ///
        ///Visit https://www.bing.com/offers/ to find more great deals or if you have any questions!
        ///
        ///-----------------------------------------------------------------------------------------------
        ///This email was sent from a notification-only address that cannot accept incoming ema [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LinkedEmailTextContent {
            get {
                return ResourceManager.GetString("LinkedEmailTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offer.
        /// </summary>
        public static string LinkedParagraph1Part1 {
            get {
                return ResourceManager.GetString("LinkedParagraph1Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is now linked to the credit cards you have added to your Bing Offers account..
        /// </summary>
        public static string LinkedParagraph1Part2 {
            get {
                return ResourceManager.GetString("LinkedParagraph1Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just pay with one of these cards to get the discount. As soon as your qualifying transaction is complete we’ll notify you..
        /// </summary>
        public static string LinkedParagraph2 {
            get {
                return ResourceManager.GetString("LinkedParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked to cards.
        /// </summary>
        public static string LinkedTitle {
            get {
                return ResourceManager.GetString("LinkedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link account.
        /// </summary>
        public static string LinkYourAccount {
            get {
                return ResourceManager.GetString("LinkYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more deals.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the Seattle area, we&apos;re trying out a new kind of offer where you don&apos;t need to buy a coupon in order to get a great deal. Bing Offers Card-Linked, is the new way to save at places that you like to eat, play, and shop. Best of all, you never have to prepay!.
        /// </summary>
        public static string MSNDealsIntro1Paragraph1 {
            get {
                return ResourceManager.GetString("MSNDealsIntro1Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Bing Offers Card-Linked discount of.
        /// </summary>
        public static string NewAuthParagraph1Part1 {
            get {
                return ResourceManager.GetString("NewAuthParagraph1Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string NewAuthParagraph1Part2 {
            get {
                return ResourceManager.GetString("NewAuthParagraph1Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is on its way..
        /// </summary>
        public static string NewAuthParagraph1Part3 {
            get {
                return ResourceManager.GetString("NewAuthParagraph1Part3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once your purchase is processed, we’ll apply the right discount to your credit or debit card ending in.
        /// </summary>
        public static string NewAuthParagraph2Part1 {
            get {
                return ResourceManager.GetString("NewAuthParagraph2Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . You should see this on your statement within three to five days of your qualifying purchase..
        /// </summary>
        public static string NewAuthParagraph2Part2 {
            get {
                return ResourceManager.GetString("NewAuthParagraph2Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string NewAuthParagraph3FAQLinkText {
            get {
                return ResourceManager.GetString("NewAuthParagraph3FAQLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember, Bing Offers Card-Linked is the new way to save at places that you like to eat, play, and shop. Best of all, you never have to prepay! Click.
        /// </summary>
        public static string NewAuthParagraph3Part1 {
            get {
                return ResourceManager.GetString("NewAuthParagraph3Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to get your questions answered and find out more..
        /// </summary>
        public static string NewAuthParagraph3Part2 {
            get {
                return ResourceManager.GetString("NewAuthParagraph3Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To track the status of your discount and see your redemption details, please verify your email address by clicking below..
        /// </summary>
        public static string NewAuthUnauthenticatedUserUnConfirmedEmailParagraph2Part1 {
            get {
                return ResourceManager.GetString("NewAuthUnauthenticatedUserUnConfirmedEmailParagraph2Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To track the status of your discount and see your redemption details, please link your email account to either a Microsoft account or Facebook login by clicking below..
        /// </summary>
        public static string NewAuthUnauthenticatedUserUnlinkedEmailParagraph2Part1 {
            get {
                return ResourceManager.GetString("NewAuthUnauthenticatedUserUnlinkedEmailParagraph2Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is not you and you think you have received this email in error, please contact .
        /// </summary>
        public static string NewAuthUnauthenticatedUserWarning {
            get {
                return ResourceManager.GetString("NewAuthUnauthenticatedUserWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Bing Offers discount of.
        /// </summary>
        public static string NewSettleParagraph1Part1 {
            get {
                return ResourceManager.GetString("NewSettleParagraph1Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string NewSettleParagraph1Part2 {
            get {
                return ResourceManager.GetString("NewSettleParagraph1Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been approved. Look for a credit of.
        /// </summary>
        public static string NewSettleParagraph1Part3 {
            get {
                return ResourceManager.GetString("NewSettleParagraph1Part3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on the statement for your credit or debit card ending in.
        /// </summary>
        public static string NewSettleParagraph1Part4 {
            get {
                return ResourceManager.GetString("NewSettleParagraph1Part4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember, Bing Offers Card-Linked is the new way to save at places that you like to eat, play, and shop. Best of all, you never have to prepay!.
        /// </summary>
        public static string NewSettleParagraph2Part1 {
            get {
                return ResourceManager.GetString("NewSettleParagraph2Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: .
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string PrivacyStatement {
            get {
                return ResourceManager.GetString("PrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.microsoft.com/fwlink/?LinkId=248686.
        /// </summary>
        public static string PrivacyStatementUrl {
            get {
                return ResourceManager.GetString("PrivacyStatementUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///Your discount of {2} at {1} is approved. Look for a credit of {3} to your credit card ending in {4} on your next statement. 
        ///
        ///Visit https://www.bing.com/offers/ to find more great deals or if you have any questions!
        ///
        ///-----------------------------------------------------------------------------------------------
        ///This email was sent from a notification-only address that cannot accept incoming email.  Please do not reply to this message.
        ///Microsoft | 1 Microsoft Way, Redmond, WA 98052 | Privacy  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SettleEmailTextContent {
            get {
                return ResourceManager.GetString("SettleEmailTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///Your Bing Offers Card-Linked discount is approved. To track the status of your discount and see your redemption details, please verify your email address by visiting this link here:  {3} .                                                                                                                                                                                                                                        If this is not you and you think you have received this email in error, please con [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SettleEmailUnAuthenticatedSignUpEmailUnconfirmedTextContent {
            get {
                return ResourceManager.GetString("SettleEmailUnAuthenticatedSignUpEmailUnconfirmedTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///Your discount of {2} at {1} is approved. To track the status of your discount and see your redemption details, please link your email account to either a Microsoft account or Facebook login by visiting this link here :  {3} .                                                                                                                                                                                                                                                                   If this is not you [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SettleEmailUnAuthenticatedSignUpEmailUnlinkedTextContent {
            get {
                return ResourceManager.GetString("SettleEmailUnAuthenticatedSignUpEmailUnlinkedTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is approved. Look for a credit of.
        /// </summary>
        public static string SettleParagraph1Part2 {
            get {
                return ResourceManager.GetString("SettleParagraph1Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on your next statement..
        /// </summary>
        public static string SettleParagraph1Part3 {
            get {
                return ResourceManager.GetString("SettleParagraph1Part3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount approved.
        /// </summary>
        public static string SettleTitle {
            get {
                return ResourceManager.GetString("SettleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is approved..
        /// </summary>
        public static string SettleUnauthenticatedUserUnconfirmedEmailParagraph1Part2 {
            get {
                return ResourceManager.GetString("SettleUnauthenticatedUserUnconfirmedEmailParagraph1Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haven&apos;t registered a card yet?.
        /// </summary>
        public static string SignUp_HaventRegistered {
            get {
                return ResourceManager.GetString("SignUp_HaventRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process is simple and takes just a few moments. &lt;a target=&apos;_blank&apos; href=&quot;{0}&quot;&gt;Do it now&lt;/a&gt; and begin getting the discounts you’re looking for!.
        /// </summary>
        public static string SignUp_ProcessSimple {
            get {
                return ResourceManager.GetString("SignUp_ProcessSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text notifications.
        /// </summary>
        public static string SignUp_TextWhenSaved {
            get {
                return ResourceManager.GetString("SignUp_TextWhenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to know you&apos;ve gotten your Bing Offers discount, and we want to tell you as soon as it happens. All we need is the phone number you use for texting. We&apos;ll send an instant &quot;you just saved&quot; text message to your cell phone. We will only text you when you&apos;ve saved money with a Bing Offers deal. Just  &lt;a target=&apos;_blank&apos; href=&quot;{0}&quot;&gt;edit your preferences&lt;/a&gt; on the &lt;b&gt;Manage Settings&lt;/b&gt; page to add your cell phone number. It&apos;s as simple as that!.
        /// </summary>
        public static string SignUp_TextWhenSavedDetails {
            get {
                return ResourceManager.GetString("SignUp_TextWhenSavedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s it! No coupons to buy in advance, no vouchers to bring with you to the merchant. We&apos;ll take care of it for you. Just walk in and use your card as you normally do. And reap the discounts!.
        /// </summary>
        public static string SignUpBottom {
            get {
                return ResourceManager.GetString("SignUpBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s how to save:.
        /// </summary>
        public static string SignUpEmailHeresHowToSave {
            get {
                return ResourceManager.GetString("SignUpEmailHeresHowToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///Thanks for signing up for Bing Offers Card-Linked. Bing Offers Card-Linked is the new way to save at places that you like to eat, play, shop or stay.
        ///
        ///To get your discount at {0}, simply pay with one of the credit cards you have added to your Bing Offers account. As soon as your qualifying transaction is complete, we’ll apply your discount to your credit card and notify you.
        ///
        ///There is nothing to print or take with you to the store – just use your card as you normally do.
        ///
        ///Visit https://www.b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SignUpEmailTextContent {
            get {
                return ResourceManager.GetString("SignUpEmailTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for signing up for Bing Offers Card-Linked. We&apos;re the new way to save at places where you eat, play, and shop. And you never have to prepay!.
        /// </summary>
        public static string SignUpParagraph1 {
            get {
                return ResourceManager.GetString("SignUpParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get your discount at.
        /// </summary>
        public static string SignUpParagraph2Part1 {
            get {
                return ResourceManager.GetString("SignUpParagraph2Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , simply link the offer at Bing Offers and then pay with one of the credit cards you have added to your account. As soon as your qualifying transaction is complete, we’ll apply your discount to your credit card and notify you..
        /// </summary>
        public static string SignUpParagraph2Part2 {
            get {
                return ResourceManager.GetString("SignUpParagraph2Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to print or take with you to the store – just use your card as you normally do..
        /// </summary>
        public static string SignUpParagraph3 {
            get {
                return ResourceManager.GetString("SignUpParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for signing up.
        /// </summary>
        public static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify email .
        /// </summary>
        public static string VerifyEmailAndLinkaccount {
            get {
                return ResourceManager.GetString("VerifyEmailAndLinkaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You work hard - treat yourself!.
        /// </summary>
        public static string WeeklyHeader {
            get {
                return ResourceManager.GetString("WeeklyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out some of our great deals just in time for a little weekend fun..
        /// </summary>
        public static string WeeklySubHeader {
            get {
                return ResourceManager.GetString("WeeklySubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Settings.
        /// </summary>
        public static string YourSettings {
            get {
                return ResourceManager.GetString("YourSettings", resourceCulture);
            }
        }
    }
}