//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace OffersEmail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Confirm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Confirm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OffersEmail.Resources.Confirm", typeof(Confirm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Offers.
        /// </summary>
        public static string BingOffers {
            get {
                return ResourceManager.GetString("BingOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.bing.com/offers/.
        /// </summary>
        public static string BingOffersUrl {
            get {
                return ResourceManager.GetString("BingOffersUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your email address.
        /// </summary>
        public static string EmailUpdateLine1 {
            get {
                return ResourceManager.GetString("EmailUpdateLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click the link below to confirm your address change. If you don&apos;t want to update your email address with Bing Offers. simply disregard this email..
        /// </summary>
        public static string EmailUpdateLine2 {
            get {
                return ResourceManager.GetString("EmailUpdateLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm updated email address.
        /// </summary>
        public static string EmailUpdateLine3 {
            get {
                return ResourceManager.GetString("EmailUpdateLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://TODO_YOUR_CDN_URL/dailydeals-assets/email.white.arrow50x50.png.
        /// </summary>
        public static string FwdButtonImageUrl {
            get {
                return ResourceManager.GetString("FwdButtonImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string Microsoft {
            get {
                return ResourceManager.GetString("Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.microsoft.com.
        /// </summary>
        public static string MicrosoftUrl {
            get {
                return ResourceManager.GetString("MicrosoftUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://TODO_YOUR_CDN_URL/dailydeals-assets/ms.logo70x15.png.
        /// </summary>
        public static string MsLogoUrl {
            get {
                return ResourceManager.GetString("MsLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://TODO_YOUR_CDN_URL/dailydeals-assets/email.logo@2x.png.
        /// </summary>
        public static string OffersLogoUrl {
            get {
                return ResourceManager.GetString("OffersLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///Please click the link below to confirm your address change. If you don&apos;t want to update your email address with Bing Offers. simply disregard this email.
        ///
        ///{0}.
        /// </summary>
        public static string UpdateEmailTextContent {
            get {
                return ResourceManager.GetString("UpdateEmailTextContent", resourceCulture);
            }
        }
    }
}