//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace OffersEmail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DailyDeals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DailyDeals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OffersEmail.Resources.DailyDeals", typeof(DailyDeals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Offers.
        /// </summary>
        public static string BingOffers {
            get {
                return ResourceManager.GetString("BingOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bing.com/offers.
        /// </summary>
        public static string BingOffersFriendlyURL {
            get {
                return ResourceManager.GetString("BingOffersFriendlyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.bing.com/offers/.
        /// </summary>
        public static string BingOffersUrl {
            get {
                return ResourceManager.GetString("BingOffersUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More savings, less effort.
        /// </summary>
        public static string CardLinkParagraph1 {
            get {
                return ResourceManager.GetString("CardLinkParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See it → Link it → Use it.
        /// </summary>
        public static string CardLinkParagraph2 {
            get {
                return ResourceManager.GetString("CardLinkParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Bing Offers Card-Linked, no more paper, no more barcodes, and no more pre-purchasing..
        /// </summary>
        public static string CardLinkParagraph3 {
            get {
                return ResourceManager.GetString("CardLinkParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change location.
        /// </summary>
        public static string ChangeLocation {
            get {
                return ResourceManager.GetString("ChangeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you continue to use Bing Offers, you&apos;re agreeing with the Terms of Use. Otherwise, please go to the &lt;a target=&apos;_blank&apos; href=&quot;{0}&quot;&gt;Bing Offers Settings page&lt;/a&gt; and click on “Close Account” to deactivate your account..
        /// </summary>
        public static string ChangeTerms_Agree {
            get {
                return ResourceManager.GetString("ChangeTerms_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions? &lt;a target=&apos;_blank&apos; href=&quot;{0}&quot;&gt;Let us know&lt;/a&gt;!.
        /// </summary>
        public static string ChangeTerms_Questions {
            get {
                return ResourceManager.GetString("ChangeTerms_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FYI.
        /// </summary>
        public static string ChangeTerms_Title {
            get {
                return ResourceManager.GetString("ChangeTerms_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve updated the Bing Offers &lt;a target=&apos;_blank&apos; href=&quot;{0}&quot;&gt;Terms of Use&lt;/a&gt; since you signed up..
        /// </summary>
        public static string ChangeTerms_Updated {
            get {
                return ResourceManager.GetString("ChangeTerms_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://TODO_YOUR_CDN_URL/dailydeals-assets/digest.email.png.
        /// </summary>
        public static string EmailIconUrl {
            get {
                return ResourceManager.GetString("EmailIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:?subject=Checkout Bing Offers website.&amp;body=http%3A%2F%2Fwww.bing.com%2Foffers%2F.
        /// </summary>
        public static string EmailShareUrl {
            get {
                return ResourceManager.GetString("EmailShareUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://TODO_YOUR_CDN_URL/dailydeals-assets/digest.facebook.png.
        /// </summary>
        public static string FacebookIconUrl {
            get {
                return ResourceManager.GetString("FacebookIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/dialog/feed?app_id=146376102206539&amp;link=http%3A%2F%2Fwww.bing.com%2Foffers&amp;picture=https%3A%2F%2Faz414848.vo.msecnd.net%2Fassets%2Fbing-offers-logo-big.png&amp;name=Bing%20Offers&amp;caption=Check%20Out%20Bing%20Offers%20Website&amp;description=Great%20deals%20and%20offers%20handpicked%20from%20around%20the%20web.&amp;redirect_uri=http%3A%2F%2Fwww.bing.com%2Foffers%3Fid%3Dfacebook-redirect&amp;display=popup&amp;show_error=true.
        /// </summary>
        public static string FacebookShareUrl {
            get {
                return ResourceManager.GetString("FacebookShareUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://bingoffers.uservoice.com/.
        /// </summary>
        public static string FeedbackUrl {
            get {
                return ResourceManager.GetString("FeedbackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like Bing Offers, get your friends and family in on the action. Let them know that Bing Offers is the best way to score local deals and save money..
        /// </summary>
        public static string GiftBottomParagraph1 {
            get {
                return ResourceManager.GetString("GiftBottomParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for being a Bing Offers pioneer!.
        /// </summary>
        public static string GiftBottomParagraph2 {
            get {
                return ResourceManager.GetString("GiftBottomParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are a few examples of great offers near you. You can see these and over 50 more offers in your area at.
        /// </summary>
        public static string GiftsExamples {
            get {
                return ResourceManager.GetString("GiftsExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Offers. The modern way to save..
        /// </summary>
        public static string GiftsHeader {
            get {
                return ResourceManager.GetString("GiftsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely,.
        /// </summary>
        public static string GiftSignaturePart1 {
            get {
                return ResourceManager.GetString("GiftSignaturePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bing Offers Team..
        /// </summary>
        public static string GiftSignaturePart2 {
            get {
                return ResourceManager.GetString("GiftSignaturePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Offers is a new kind of deal where you don&apos;t need to buy a coupon or present a voucher at the restaurants and stores you visit. The discounts are automatically applied to your credit card. With Bing Offers you save at the places you like to eat, play and shop. And best of all you NEVER pre-pay!.
        /// </summary>
        public static string GiftsParagraph1 {
            get {
                return ResourceManager.GetString("GiftsParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a limited time we are offering Starbucks gift cards to anyone who signs up or redeems an offer. Hurry! This promotion is limited to the first 500 participants..
        /// </summary>
        public static string GiftsParagraph2 {
            get {
                return ResourceManager.GetString("GiftsParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get great savings without paying in advance or printing coupons..
        /// </summary>
        public static string GiftsSubHeader {
            get {
                return ResourceManager.GetString("GiftsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up at.
        /// </summary>
        public static string HowToSaveParagraph1part1 {
            get {
                return ResourceManager.GetString("HowToSaveParagraph1part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and discover all the great deals in your area..
        /// </summary>
        public static string HowToSaveParagraph1part2 {
            get {
                return ResourceManager.GetString("HowToSaveParagraph1part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit any participating business and make a qualifying purchase using one of the credit or debit card you registered during signup..
        /// </summary>
        public static string HowToSaveParagraph2 {
            get {
                return ResourceManager.GetString("HowToSaveParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll receive an instant notification on your mobile phone that you saved, and the discount will appear on your next credit card statement..
        /// </summary>
        public static string HowToSaveParagraph3 {
            get {
                return ResourceManager.GetString("HowToSaveParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link offer.
        /// </summary>
        public static string LinkOffer {
            get {
                return ResourceManager.GetString("LinkOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ssl.bing.com/offers/cardlinkedwizard.
        /// </summary>
        public static string LinkOfferUrl {
            get {
                return ResourceManager.GetString("LinkOfferUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string Microsoft {
            get {
                return ResourceManager.GetString("Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Corporation, 1 Microsoft Way, Redmond, WA 98052, USA.
        /// </summary>
        public static string MicrosoftAddress {
            get {
                return ResourceManager.GetString("MicrosoftAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.microsoft.com.
        /// </summary>
        public static string MicrosoftUrl {
            get {
                return ResourceManager.GetString("MicrosoftUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more fabulous deals at Bing Offers.
        /// </summary>
        public static string MoreDealsText {
            get {
                return ResourceManager.GetString("MoreDealsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://TODO_YOUR_CDN_URL/dailydeals-assets/ms.logo70x15.png.
        /// </summary>
        public static string MsLogoUrl {
            get {
                return ResourceManager.GetString("MsLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSN Offers is now Bing Offers.
        /// </summary>
        public static string MsnParagraph1 {
            get {
                return ResourceManager.GetString("MsnParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get big savings on local deals.
        /// </summary>
        public static string MsnParagraph2 {
            get {
                return ResourceManager.GetString("MsnParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Offers brings together popular deals from across the web, creating a simple way for you to discover and take advantage of great local deals..
        /// </summary>
        public static string MsnParagraph3 {
            get {
                return ResourceManager.GetString("MsnParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://TODO_YOUR_CDN_URL/dailydeals-assets/300x350_msn_email.jpg.
        /// </summary>
        public static string MsnSplashImage {
            get {
                return ResourceManager.GetString("MsnSplashImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://TODO_YOUR_CDN_URL/dailydeals-assets/email.logo@2x.png.
        /// </summary>
        public static string OffersLogoUrl {
            get {
                return ResourceManager.GetString("OffersLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Offers Daily Deals.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinterest.
        /// </summary>
        public static string Pinterest {
            get {
                return ResourceManager.GetString("Pinterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://TODO_YOUR_CDN_URL/dailydeals-assets/digest.pinterest.png.
        /// </summary>
        public static string PinterestIconUrl {
            get {
                return ResourceManager.GetString("PinterestIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fwww.bing.com%2Foffers%2F&amp;media=https%3A%2F%2Faz414848.vo.msecnd.net%2Fassets%2Fbing-offers-logo-big.png&amp;description=Checkout%20Bing%20Offers%20website..
        /// </summary>
        public static string PinterestShareUrl {
            get {
                return ResourceManager.GetString("PinterestShareUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statements.
        /// </summary>
        public static string PrivacyStatements {
            get {
                return ResourceManager.GetString("PrivacyStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://go.microsoft.com/fwlink/?LinkId=248686.
        /// </summary>
        public static string PrivacyStatementsUrl {
            get {
                return ResourceManager.GetString("PrivacyStatementsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string SaveHeader {
            get {
                return ResourceManager.GetString("SaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEND.
        /// </summary>
        public static string SpendHeader {
            get {
                return ResourceManager.GetString("SpendHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are receiving this email because you have signed up to receive Bing Offers communications. If you prefer not to receive future offer emails, use the link below to unsubscribe..
        /// </summary>
        public static string SubscriptionText {
            get {
                return ResourceManager.GetString("SubscriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://g.msn.com/1ewbingwin8/settingsTOUen-US.
        /// </summary>
        public static string TermsConditionsUrl {
            get {
                return ResourceManager.GetString("TermsConditionsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://TODO_YOUR_CDN_URL/dailydeals-assets/digest.twitter.png.
        /// </summary>
        public static string TwitterIconUrl {
            get {
                return ResourceManager.GetString("TwitterIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/share?url=http%3A%2F%2Fwww.bing.com%2Foffers%2F&amp;text=Check%20out%20Bing%20offers%20website&amp;via=BingOffers&amp;hashtags=BingOffers.
        /// </summary>
        public static string TwitterShareUrl {
            get {
                return ResourceManager.GetString("TwitterShareUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALUE.
        /// </summary>
        public static string ValueHeader {
            get {
                return ResourceManager.GetString("ValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View offer.
        /// </summary>
        public static string ViewOffer {
            get {
                return ResourceManager.GetString("ViewOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Bing Offers.
        /// </summary>
        public static string VisitBingOffers {
            get {
                return ResourceManager.GetString("VisitBingOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Card-Linked Offers.
        /// </summary>
        public static string VisitCardLinkedOffers {
            get {
                return ResourceManager.GetString("VisitCardLinkedOffers", resourceCulture);
            }
        }
    }
}