//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace OffersEmail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Earn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Earn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OffersEmail.Resources.Earn", typeof(Earn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your purchase from Microsoft! A credit of {0} will appear on your next card statement! http://aka.ms/tranhist.
        /// </summary>
        public static string BurnSmsTemplate {
            get {
                return ResourceManager.GetString("BurnSmsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congrats! You just received {0}% in Earn Credits from {1}. Earn DOUBLE this weekend only! http://aka.ms/tranhist.
        /// </summary>
        public static string DoubleEarnSmsTemplate {
            get {
                return ResourceManager.GetString("DoubleEarnSmsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congrats! You just received {0}% in Earn Credits from your purchase at {1}. See your transactions at http://aka.ms/tranhist.
        /// </summary>
        public static string EarnSmsTemplate {
            get {
                return ResourceManager.GetString("EarnSmsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congrats...
        ///
        ///You just picked up {0}% in Earn Credits from your purchase at {1}. Sweet!
        ///
        ///Earn... the new way to Earn Credits at the places you love, for the technologies you want.   
        ///
        ///Happy Earning!
        ///
        ///Earn, by Microsoft Advertising
        ///
        ///Visit https://www.earnbymicrosoft.com/ to learn more!
        ///
        ///----------------------------------------------------------------------------------------------------------------------------
        ///This email was sent from a notification-only address that cannot accept incoming email.  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EarnTextTemplate {
            get {
                return ResourceManager.GetString("EarnTextTemplate", resourceCulture);
            }
        }
    }
}