//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace OffersEmail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MerchantReportEmail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MerchantReportEmail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OffersEmail.Resources.MerchantReportEmail", typeof(MerchantReportEmail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions or need clarifications, please do not hesitate to get in touch with us at &lt;a href=&quot;mailto:BingOffersSupport@Microsoft.com&quot;&gt;BingOffersSupport@Microsoft.com&lt;/a&gt; or call us at (425) 247 – 0523..
        /// </summary>
        public static string AnyQuestions {
            get {
                return ResourceManager.GetString("AnyQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Regards.
        /// </summary>
        public static string BestRegards {
            get {
                return ResourceManager.GetString("BestRegards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BingOffersSupport@Microsoft.com.
        /// </summary>
        public static string BingOffersSupportEmailId {
            get {
                return ResourceManager.GetString("BingOffersSupportEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bing Offers Team.
        /// </summary>
        public static string BingOffersTeam {
            get {
                return ResourceManager.GetString("BingOffersTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And remember, you can return to the &lt;a href=&quot;http://bing.com/offers/merchant/dashboard&quot;&gt;Merchant portal&lt;/a&gt;  anytime to create or edit the offers you are running..
        /// </summary>
        public static string CommonEnding {
            get {
                return ResourceManager.GetString("CommonEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or call us at (425) 247 – 0523.
        /// </summary>
        public static string OrCallUsAt {
            get {
                return ResourceManager.GetString("OrCallUsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once again, thank you for your continued support of Bing Offers..
        /// </summary>
        public static string ThanksOnceAgain {
            get {
                return ResourceManager.GetString("ThanksOnceAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Offers.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you again for taking part in the Bing Offers Card-Linked program. This is your transaction report for .
        /// </summary>
        public static string TransactionReportFor {
            get {
                return ResourceManager.GetString("TransactionReportFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your preference for how often you receive this report can be changed anytime at our &lt;a href=&quot;http://bing.com/offers/merchant/dashboard&quot;&gt;Merchant portal&lt;/a&gt;..
        /// </summary>
        public static string TransactionReportPreference {
            get {
                return ResourceManager.GetString("TransactionReportPreference", resourceCulture);
            }
        }
    }
}