//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

namespace Earn.Dashboard.DAL.db.Analytics
{
    using System;
    using System.Collections.Generic;
    
    public partial class analytic
    {
        public long Id { get; set; }
        public string AuthenticatedUserId { get; set; }
        public System.Guid BrowserId { get; set; }
        public string IPAddress { get; set; }
        public System.Guid SessionId { get; set; }
        public string DeviceType { get; set; }
        public string UserAgent { get; set; }
        public string PageTitle { get; set; }
        public System.DateTime ServerTimeStamp { get; set; }
        public string PageUrl { get; set; }
        public string EventId { get; set; }
        public string EventType { get; set; }
        public string EventInfo { get; set; }
        public string FlightId { get; set; }
        public Nullable<bool> NewUser { get; set; }
        public Nullable<bool> IsAuthenticated { get; set; }
        public string cmp_source { get; set; }
        public string cmp_name { get; set; }
        public string cmp_ref { get; set; }
    }
}