//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace Lomo.Commerce.Service.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddCardClientResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddCardClientResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lomo.Commerce.Service.Client.Resources.AddCardClientResource", typeof(AddCardClientResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddCard_Add {
            get {
                return ResourceManager.GetString("AddCard_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Card.
        /// </summary>
        public static string AddCard_AddCard {
            get {
                return ResourceManager.GetString("AddCard_AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string AddCard_CardMonth {
            get {
                return ResourceManager.GetString("AddCard_CardMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card number.
        /// </summary>
        public static string AddCard_CardNumber {
            get {
                return ResourceManager.GetString("AddCard_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARD.
        /// </summary>
        public static string AddCard_CardTitle {
            get {
                return ResourceManager.GetString("AddCard_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of credit card.
        /// </summary>
        public static string AddCard_CardType {
            get {
                return ResourceManager.GetString("AddCard_CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string AddCard_CardYear {
            get {
                return ResourceManager.GetString("AddCard_CardYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don’t prepay and we aren’t charging your card for anything. When you make a qualifying purchase, the discount will automatically be applied to your credit or debit card statement in 3 to 5 days..
        /// </summary>
        public static string AddCard_Description1 {
            get {
                return ResourceManager.GetString("AddCard_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddCard_Description2 {
            get {
                return ResourceManager.GetString("AddCard_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Visa or MasterCard number.
        /// </summary>
        public static string AddCard_Enter_Card_Num {
            get {
                return ResourceManager.GetString("AddCard_Enter_Card_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPIRATION.
        /// </summary>
        public static string AddCard_ExpiryTitle {
            get {
                return ResourceManager.GetString("AddCard_ExpiryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a card.
        /// </summary>
        public static string AddCard_Header {
            get {
                return ResourceManager.GetString("AddCard_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE.
        /// </summary>
        public static string AddCard_ManageTitle {
            get {
                return ResourceManager.GetString("AddCard_ManageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cards.
        /// </summary>
        public static string AddCard_MyCardsTitle {
            get {
                return ResourceManager.GetString("AddCard_MyCardsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card description.
        /// </summary>
        public static string AddCard_Name {
            get {
                return ResourceManager.GetString("AddCard_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the cards you would like associated with your Card-Linked account. Note: American Express support coming soon..
        /// </summary>
        public static string AddCard_Reminder_Description {
            get {
                return ResourceManager.GetString("AddCard_Reminder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your card will not be charged at any time by Bing Offers..
        /// </summary>
        public static string AddCard_Reminder_DescriptionBold {
            get {
                return ResourceManager.GetString("AddCard_Reminder_DescriptionBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMINDER.
        /// </summary>
        public static string AddCard_Reminder_Header {
            get {
                return ResourceManager.GetString("AddCard_Reminder_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Card.
        /// </summary>
        public static string AddCard_RemoveCard {
            get {
                return ResourceManager.GetString("AddCard_RemoveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a card.
        /// </summary>
        public static string AddCard_Right_Header {
            get {
                return ResourceManager.GetString("AddCard_Right_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amex.
        /// </summary>
        public static string Amex {
            get {
                return ResourceManager.GetString("Amex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: American Express support coming soon..
        /// </summary>
        public static string AmexSupportMessage {
            get {
                return ResourceManager.GetString("AmexSupportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04-April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08-August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-December.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        public static string email_invalid_error {
            get {
                return ResourceManager.GetString("email-invalid-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don’t currently support American Express credit cards..
        /// </summary>
        public static string Error_AmericanExpress {
            get {
                return ResourceManager.GetString("Error_AmericanExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That isn’t a valid credit or debit card number..
        /// </summary>
        public static string Error_InvalidCard {
            get {
                return ResourceManager.GetString("Error_InvalidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please try again.
        /// </summary>
        public static string Error_Unknown {
            get {
                return ResourceManager.GetString("Error_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02-February.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a valid expiration month.
        /// </summary>
        public static string InvalidMonth {
            get {
                return ResourceManager.GetString("InvalidMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid name.
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a valid expiration year.
        /// </summary>
        public static string InvalidYear {
            get {
                return ResourceManager.GetString("InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01-January.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 07-July.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 06-June.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03-March.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterCard.
        /// </summary>
        public static string MasterCard {
            get {
                return ResourceManager.GetString("MasterCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05-May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name on card.
        /// </summary>
        public static string NameOnCard {
            get {
                return ResourceManager.GetString("NameOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11-November.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10-October.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09-September.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to accept the terms..
        /// </summary>
        public static string TermsNotAcceptedError {
            get {
                return ResourceManager.GetString("TermsNotAcceptedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        public static string Visa {
            get {
                return ResourceManager.GetString("Visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2013.
        /// </summary>
        public static string Year2013 {
            get {
                return ResourceManager.GetString("Year2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2014.
        /// </summary>
        public static string Year2014 {
            get {
                return ResourceManager.GetString("Year2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015.
        /// </summary>
        public static string Year2015 {
            get {
                return ResourceManager.GetString("Year2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016.
        /// </summary>
        public static string Year2016 {
            get {
                return ResourceManager.GetString("Year2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2017.
        /// </summary>
        public static string Year2017 {
            get {
                return ResourceManager.GetString("Year2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018.
        /// </summary>
        public static string Year2018 {
            get {
                return ResourceManager.GetString("Year2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019.
        /// </summary>
        public static string Year2019 {
            get {
                return ResourceManager.GetString("Year2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020.
        /// </summary>
        public static string Year2020 {
            get {
                return ResourceManager.GetString("Year2020", resourceCulture);
            }
        }
    }
}