//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

namespace Earn.Dashboard.DAL.db.Commerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card()
        {
            this.ARCHIVE_PartnerCards = new HashSet<ARCHIVE_PartnerCards>();
            this.ClaimedDealBatches = new HashSet<ClaimedDealBatch>();
            this.TransactionLinks = new HashSet<TransactionLink>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string LastFourDigits { get; set; }
        public System.DateTime UtcAdded { get; set; }
        public bool Active { get; set; }
        public System.DateTime UtcUpdated { get; set; }
        public int CardBrand { get; set; }
        public int Flags { get; set; }
        public string PartnerToken { get; set; }
        public string FDCToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARCHIVE_PartnerCards> ARCHIVE_PartnerCards { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimedDealBatch> ClaimedDealBatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLink> TransactionLinks { get; set; }
    }
}