//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

namespace Earn.Dashboard.DAL.db.Commerce
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommerceEntities : DbContext
    {
        public CommerceEntities()
            : base("name=CommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARCHIVE_PartnerCards> ARCHIVE_PartnerCards { get; set; }
        public virtual DbSet<ARCHIVE_PartnerUsers> ARCHIVE_PartnerUsers { get; set; }
        public virtual DbSet<Authorization> Authorizations { get; set; }
        public virtual DbSet<CardBrand> CardBrands { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<ClaimedDealBatch> ClaimedDealBatches { get; set; }
        public virtual DbSet<CreditStatu> CreditStatus { get; set; }
        public virtual DbSet<DealBatch> DealBatches { get; set; }
        public virtual DbSet<DealPartnerMerchantId> DealPartnerMerchantIds { get; set; }
        public virtual DbSet<Deal> Deals { get; set; }
        public virtual DbSet<DealStatu> DealStatus { get; set; }
        public virtual DbSet<EventLog> EventLogs { get; set; }
        public virtual DbSet<MerchantName> MerchantNames { get; set; }
        public virtual DbSet<Merchant> Merchants { get; set; }
        public virtual DbSet<MSSVDistribution> MSSVDistributions { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<PartnerCardFilter> PartnerCardFilters { get; set; }
        public virtual DbSet<PartnerDealRegistrationStatu> PartnerDealRegistrationStatus { get; set; }
        public virtual DbSet<PartnerDeal> PartnerDeals { get; set; }
        public virtual DbSet<PartnerMerchantAuthorizationID> PartnerMerchantAuthorizationIDs { get; set; }
        public virtual DbSet<PartnerMerchantIdType> PartnerMerchantIdTypes { get; set; }
        public virtual DbSet<PartnerMerchantSettlementID> PartnerMerchantSettlementIDs { get; set; }
        public virtual DbSet<PartnerRedeemedDeal> PartnerRedeemedDeals { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<PartnerUserID> PartnerUserIDs { get; set; }
        public virtual DbSet<PayeeType> PayeeTypes { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<RedeemedDeal> RedeemedDeals { get; set; }
        public virtual DbSet<RedemptionEvent> RedemptionEvents { get; set; }
        public virtual DbSet<ReferralEventReward> ReferralEventRewards { get; set; }
        public virtual DbSet<ReferralEvent> ReferralEvents { get; set; }
        public virtual DbSet<Referral> Referrals { get; set; }
        public virtual DbSet<ReferralType> ReferralTypes { get; set; }
        public virtual DbSet<ReferralVector> ReferralVectors { get; set; }
        public virtual DbSet<ReferrerType> ReferrerTypes { get; set; }
        public virtual DbSet<ReimbursementTender> ReimbursementTenders { get; set; }
        public virtual DbSet<RewardPayout> RewardPayouts { get; set; }
        public virtual DbSet<RewardPayoutStatu> RewardPayoutStatus { get; set; }
        public virtual DbSet<RewardProgram> RewardPrograms { get; set; }
        public virtual DbSet<RewardReason> RewardReasons { get; set; }
        public virtual DbSet<RewardRecipient> RewardRecipients { get; set; }
        public virtual DbSet<Reward> Rewards { get; set; }
        public virtual DbSet<RewardType> RewardTypes { get; set; }
        public virtual DbSet<Sequence> Sequences { get; set; }
        public virtual DbSet<TrackedRedemptionReward> TrackedRedemptionRewards { get; set; }
        public virtual DbSet<TransactionLink> TransactionLinks { get; set; }
        public virtual DbSet<TransactionReviewStatu> TransactionReviewStatus { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<RedemptionReport> RedemptionReports { get; set; }
    }
}