//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

namespace Earn.Dashboard.DAL.db.Commerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deal()
        {
            this.DealPartnerMerchantIds = new HashSet<DealPartnerMerchantId>();
            this.PartnerDeals = new HashSet<PartnerDeal>();
            this.TransactionLinks = new HashSet<TransactionLink>();
            this.DealBatches = new HashSet<DealBatch>();
        }
    
        public int Id { get; set; }
        public System.Guid GlobalId { get; set; }
        public string MerchantId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Currency { get; set; }
        public int Amount { get; set; }
        public decimal Percent { get; set; }
        public int MinimumPurchase { get; set; }
        public int Count { get; set; }
        public int UserLimit { get; set; }
        public string DiscountSummary { get; set; }
        public int MaximumDiscount { get; set; }
        public Nullable<System.Guid> ParentDealId { get; set; }
        public Nullable<System.DateTime> DateIngestedUtc { get; set; }
        public int DealStatusId { get; set; }
        public Nullable<int> MerchantNameId { get; set; }
        public string DayTimeRestrictions { get; set; }
        public int ReimbursementTenderId { get; set; }
        public string ProviderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealPartnerMerchantId> DealPartnerMerchantIds { get; set; }
        public virtual DealStatu DealStatu { get; set; }
        public virtual MerchantName MerchantName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerDeal> PartnerDeals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLink> TransactionLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealBatch> DealBatches { get; set; }
    }
}