//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

namespace Earn.Dashboard.DAL.db.Commerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Merchant()
        {
            this.PartnerMerchantAuthorizationIDs = new HashSet<PartnerMerchantAuthorizationID>();
            this.PartnerMerchantSettlementIDs = new HashSet<PartnerMerchantSettlementID>();
        }
    
        public int Id { get; set; }
        public string GlobalID { get; set; }
        public string Name { get; set; }
        public int ProviderId { get; set; }
        public System.DateTime UtcAdded { get; set; }
        public System.DateTime UtcUpdated { get; set; }
    
        public virtual Provider Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerMerchantAuthorizationID> PartnerMerchantAuthorizationIDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerMerchantSettlementID> PartnerMerchantSettlementIDs { get; set; }
    }
}