//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

namespace Earn.Dashboard.DAL.db.Commerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerDeal
    {
        public int PartnerId { get; set; }
        public string PartnerDealId { get; set; }
        public int DealId { get; set; }
        public int PartnerDealRegistrationStatusId { get; set; }
    
        public virtual Deal Deal { get; set; }
        public virtual PartnerDealRegistrationStatu PartnerDealRegistrationStatu { get; set; }
        public virtual Partner Partner { get; set; }
    }
}