//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

namespace Earn.Dashboard.DAL.db.Commerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedeemedDeal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RedeemedDeal()
        {
            this.PartnerRedeemedDeals = new HashSet<PartnerRedeemedDeal>();
            this.TrackedRedemptionRewards = new HashSet<TrackedRedemptionReward>();
        }
    
        public System.Guid Id { get; set; }
        public long ClaimedDealId { get; set; }
        public int RedemptionEventId { get; set; }
        public System.DateTime PurchaseDateTime { get; set; }
        public int AuthorizationAmount { get; set; }
        public string Currency { get; set; }
        public bool Reversed { get; set; }
        public int CreditStatusId { get; set; }
        public int DiscountAmount { get; set; }
        public int SettlementAmount { get; set; }
        public Nullable<System.Guid> AnalyticsRedemptionEventId { get; set; }
        public Nullable<System.Guid> AnalyticsSettlementEventId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateSettled { get; set; }
        public Nullable<System.DateTime> DateCreditApproved { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateUtc { get; set; }
        public bool PermaPending { get; set; }
        public int ReviewStatusId { get; set; }
        public int MerchantNameId { get; set; }
        public Nullable<System.DateTime> UtcReachedTerminalState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerRedeemedDeal> PartnerRedeemedDeals { get; set; }
        public virtual TransactionLink TransactionLink { get; set; }
        public virtual RedemptionEvent RedemptionEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackedRedemptionReward> TrackedRedemptionRewards { get; set; }
    }
}