//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

namespace Earn.Dashboard.DAL.db.Commerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackedRedemptionReward
    {
        public int Id { get; set; }
        public System.Guid RedeemedDealId { get; set; }
        public System.Guid RewardPayoutId { get; set; }
    
        public virtual RedeemedDeal RedeemedDeal { get; set; }
        public virtual RewardPayout RewardPayout { get; set; }
    }
}