//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

namespace Earn.Dashboard.LomoUsersDAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSchedulesHistory
    {
        public int HistoryId { get; set; }
        public int Id { get; set; }
        public int TemplateId { get; set; }
        public int TargetId { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public short Recurrence { get; set; }
        public Nullable<System.DateTime> NextRunDate { get; set; }
        public bool IsActive { get; set; }
        public string Metadata { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual EmailTarget EmailTarget { get; set; }
        public virtual EmailTemplate EmailTemplate { get; set; }
    }
}