//
// Copyright (c) Microsoft Corporation. All rights reserved. 
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//

// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

namespace Earn.Dashboard.LomoUsersDAL.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LomoUsersEntities : DbContext
    {
        public LomoUsersEntities()
            : base("name=LomoUsersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConfirmationCode> ConfirmationCodes { get; set; }
        public virtual DbSet<EmailCampaign> EmailCampaigns { get; set; }
        public virtual DbSet<EmailDataContract> EmailDataContracts { get; set; }
        public virtual DbSet<EmailJob> EmailJobs { get; set; }
        public virtual DbSet<EmailSchedule> EmailSchedules { get; set; }
        public virtual DbSet<EmailSchedulesHistory> EmailSchedulesHistories { get; set; }
        public virtual DbSet<EmailSubscription> EmailSubscriptions { get; set; }
        public virtual DbSet<EmailSubscriptionsHistory> EmailSubscriptionsHistories { get; set; }
        public virtual DbSet<EmailTarget> EmailTargets { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<EmailTemplateType> EmailTemplateTypes { get; set; }
        public virtual DbSet<EmailUnsubscribeUrl> EmailUnsubscribeUrls { get; set; }
        public virtual DbSet<EventLog> EventLogs { get; set; }
        public virtual DbSet<ExternalUser> ExternalUsers { get; set; }
        public virtual DbSet<ExternalUsersHistory> ExternalUsersHistories { get; set; }
        public virtual DbSet<MerchantSubscription> MerchantSubscriptions { get; set; }
        public virtual DbSet<MerchantSubscriptionsHistory> MerchantSubscriptionsHistories { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<UserConfirmEmailResendsHistory> UserConfirmEmailResendsHistories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersHistory> UsersHistories { get; set; }
        public virtual DbSet<UsersLocation> UsersLocations { get; set; }
        public virtual DbSet<ActiveEmailJobsView> ActiveEmailJobsViews { get; set; }
        public virtual DbSet<EmailSubscriptionsCurrentView> EmailSubscriptionsCurrentViews { get; set; }
        public virtual DbSet<ExecStat> ExecStats { get; set; }
        public virtual DbSet<ValidMerchantUsersView> ValidMerchantUsersViews { get; set; }
        public virtual DbSet<ValidUsersView> ValidUsersViews { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<script_deployment_status> script_deployment_status { get; set; }
        public virtual DbSet<script_deployments> script_deployments { get; set; }
    }
}